print('vinit sharma')
a = ( input ("Enter the value of a: "))
b = ( input ("Enter the value of b: "))
c = int(a) / int(b)
print("division",c)
quotient = int(a) // int(b)
remainder = int(a) % int(b)
print("quotient",quotient)
print("remainder",remainder)